# Generated by Django 4.2.2 on 2023-06-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='user',
        ),
    ]
